# Generated by Django 2.2.6 on 2019-10-18 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserInterface', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='apply_service',
            new_name='ConfigurationFile',
        ),
    ]
